### ISSUE TITLE
provide startWith operator taking a function to provide the value

### ISSUE THREAD

**Issue by Stychlok** [w11k/rx-ninja#28]
... because the value should be defined as soon as a subscriber subscribes not before

**Comment by pburgmer** [comment]
I will implement it soon

**Comment by pburgmer** [comment]
Implemented. But I'm not able to publish. We need your help @romanroe

**Comment by pburgmer** [comment]
Will be released with version 4.6.0

**Comment by Stychlok** [comment]
Did you forget to export this function in src/index.ts?

**Comment by pburgmer** [comment]
Yes, damn! Anfängerfehler

Stychlok ***@***.***> schrieb am Fr., 28. Okt. 2022, 17:54:

**Comment by Stychlok** [comment]
Let me know when there's a new version.

**Comment by romanroe** [comment]
@Stychlok Done! Version 4.6.1
