### ISSUE TITLE
rulesDirectory in documentation is not valid anymore

### ISSUE THREAD

**Issue by mickaeltr** [w11k/rx-ninja#5]
Hello,

I updated my project to the latest version of rx-ninja and noticed that rules are not available anymore under: node_modules/@w11k/rx-ninja/dist/tslint_rules

There are now 3 subdirectories (bundle, esm5, esm2015). I set `node_modules/@w11k/rx-ninja/dist/tslint_rules/bundle` and it worked again.

Cheers

**Comment by romanroe** [comment]
@mickaeltr Thanks for catching that! I changed the README accordingly.
