### ISSUE TITLE
Feature request: file suffix exclusion

### ISSUE THREAD

**Issue by mickaeltr** [w11k/rx-ninja#8]
Hello,

Currently, I have `// tslint:disable:rx-ninja-subscribe-takeuntil` in most of my test files.

So I thought it would be nice to have the ability to exclude files (eg. `.spec.ts`).

Cheers

**Comment by romanroe** [comment]
Good idea!

We added a similar feature in the latest version (https://github.com/w11k/rx-ninja#rule-descriptions). However, this was about which files to include (e.g. only Angular components) and not which files to *exclude* (your use case).

We could either

a) add a "excludeFileSuffix" configuration property

```
"rx-ninja-subscribe-takeuntil": [
    true,
    {
        "finalizer": [...],
        "fileSuffix": [
            ".component.ts"
        ],
        "excludeFileSuffix": [
            ".spec.ts"
        ]
    }
]
```

or 

b) use a trailing ! to exclude a file pattern

```
"rx-ninja-subscribe-takeuntil": [
    true,
    {
        "finalizer": [...],
        "fileSuffix": [
             ".component.ts",
            "!.spec.ts"
        ]
    }
]
```

@mickaeltr @sengmann @pburgmer @kaihenzler  Which do you prefer?

**Comment by kaihenzler** [comment]
@romanroe I would vote for adding an extra property for exclusion

**Comment by mickaeltr** [comment]
+1 for the extra property, it seems less confusing to me

Thanks for your responsiveness 👍

**Comment by romanroe** [comment]
@mickaeltr There goes my responsiveness 🙈🙈🙈

I added this property in 4.3.0

https://github.com/w11k/rx-ninja#rule-descriptions
https://github.com/w11k/rx-ninja/releases/tag/v4.3.0
